[package]
name = "users"
version = "0.1.0"

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rocket_contrib = { version = "0.3.3", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
