version: '3'
services:
  # Postgres
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=users
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=users
    ports:
      - 5432:5432
  # Users
  users:
    image: users
    build:
      context: .
    command: ["sh", "-c", "diesel setup; users"]  
    environment:
      - RUST_LOG=info
      - RUN_MODE=docker
      - DATABASE_URL=postgresql://users:users@postgres/users
    ports:
      - 8000:8000
    depends_on:
      - postgres