[development]
address = "localhost"
port    = 3000
workers = 1
log     = "normal"
redis   = "redis://localhost:6379"

[staging]
address = "0.0.0.0"
port    = 80
log     = "normal"
workers = 8
redis   = "redis://0.0.0.0:6379"
