FROM rust:1.24.1-stretch

# Install libpq-10
RUN wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add - && \
    sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list.d/pgdg.list' && \
    apt-get update && \
    apt-get install -y libpq-dev

COPY . /app
WORKDIR /app

# Install diesel client
RUN cargo install diesel_cli

RUN cargo build --release --locked
