version: '3'
services:
  users:
    image: rust
    build:
      context: ..
      dockerfile: docker/Dockerfile.rust
    container_name: users
    environment:
      - RUST_LOG=info
    volumes:
      - ..:/app
      - stq_cargo_cache:/usr/local/cargo
    ports:
      - 8000:8000
    stdin_open: true
    tty: true

volumes:
  stq_cargo_cache:

networks:
  default:
    external:
      name: storiqa