version: '3'
services:
  users:
    image: users
    build:
      context: .
      dockerfile: Dockerfile.users
    container_name: users
    working_dir: /app
    command: ["sh", "-c", "/utils/wait_for_it.sh users-pg:5432 ; diesel migration run ; cargo run --locked"]
    volumes:
      - ..:/app
      - stq_cargo_cache:/usr/local/cargo
    environment:
      - DATABASE_URL=postgresql://users:users@users-pg/users
      - "RUST_LOG=users=debug,stq_http=debug"
    ports:
      - "8000"
    expose:
      - 8000
    stdin_open: true
    depends_on:
      - users-pg
      - users-redis

  users-pg:
    image: postgres:10
    container_name: users-pg
    volumes:
      - stq_users_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=users
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=users
    ports:
      - "5432"
    expose:
      - 5432

  users-redis:
    image: redis:4.0-alpine
    container_name: users-redis
    volumes:
      - stq_users_redis_data:/data
    ports:
      - "6379"
    expose:
      - 6379

volumes:
  stq_cargo_cache:
  stq_users_postgres_data:
  stq_users_redis_data:

networks:
  default:
    external:
      name: storiqa
