version: '3'
services:
  users:
    image: users
    build:
      context: .
      dockerfile: Dockerfile.users
    container_name: users
    working_dir: /app
    command: ["sh", "-c", "/utils/wait_for_it.sh users-pg:5432 ; diesel migration run ; cargo run"]
    volumes:
      - ..:/app
      - stq_cargo_cache:/usr/local/cargo
    environment:
      - DATABASE_URL=postgresql://users:users@users-pg/users
      - "RUST_LOG=users=debug"
    ports:
      - "8000"
    expose:
      - 8000
    stdin_open: true
    depends_on:
      - users-pg

  users-pg:
    image: postgres:10
    container_name: users-pg
    volumes:
      - stq-users-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=users
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=users
    expose:
      - 5432

volumes:
  stq_cargo_cache:
  stq-users-postgres-data:

networks:
  default:
    external:
      name: storiqa
