[server]
host = "0.0.0.0"
port = "8000"
database = "postgresql://users:users@users-pg/users"
thread_count = 20

[client]
http_client_buffer_size=3
http_client_retries=3
dns_worker_thread_count=4
http_timeout_ms=15000
