[server]
host = "0.0.0.0"
port = "8000"
database = "postgresql://users:users@users-pg/users"
# redis = "redis://users-redis"
thread_count = 20
cache_ttl_sec = 600
# processing_timeout_ms = 1000

[client]
http_client_buffer_size = 3
http_client_retries = 3
http_timeout_ms = 15000
dns_worker_thread_count = 4
