[jwt]
secret_key = "jwt secret key"

[google]
info_url = "https://www.googleapis.com/userinfo/v2/me"

[facebook]
info_url = "https://graph.facebook.com/me"

[saga_addr]
url = "http://saga:8004"

[notifications]
url = "http://notifications:8005"
sendmail_path = "sendmail"
link_path = "https://localhost/password_reset"
