[jwt]
secret_key = "jwt secret key"

[google]
id = "google id"
key = "google key"
url = "https://www.googleapis.com/oauth2/v3/tokeninfo"

[facebook]
id = "facebook id"
key = "facebook key"
url = "https://graph.facebook.com/me"
